### PR TITLE
Sreeraj/feature: improvements status note

### PR DESCRIPTION
**Pull request by djsreeraj**

### CODE REVIEW

**Comment by djsreeraj** [comment]
[Add Notes capability in the orderstatus change option.](https://trello.com/c/PAduHJca/245-add-notes-capability-in-the-orderstatus-change-option)

**Comment by djsreeraj** [comment]
[place order page manage lengthy text - img shrink](https://trello.com/c/8MbO2g67/321-place-order-page-manage-lengthy-text-img-shrink)

**Comment by djsreeraj** [comment]
[Status code icon color difference in first and second page](https://trello.com/c/9m7F7lDU/320-status-code-icon-color-difference-in-first-and-second-page)

**Comment by djsreeraj** [comment]
[Filters, grouping](https://trello.com/c/8n9F0Ezq/174-filters-grouping)

**Comment by djsreeraj** [comment]
[Issue: Check on second long press effect](https://trello.com/c/24jwsr2d/230-issue-check-on-second-long-press-effect)

**Review by kirananto — APPROVED** [review]

**Pull request merged**
